### PR TITLE
cast to uv_after_work_cb for Node 0.10

### PR DESCRIPTION
**Pull request by rvagg**
otherwise it won't compile

### CODE REVIEW

**Comment by wemakeweb** [comment]
+1

**Comment by scriby** [comment]
+1

Can't move to node v0.10 without this.

**Comment by scriby** [comment]
Are you planning on updating npm with this change?

**Comment by lloyd** [comment]
Updated.  Try v0.2.2

-- lloyd (thumb-typing)

**Comment by scriby** [comment]
Thanks!

On Mar 13, 2013, at 7:31 PM, Lloyd Hilaiel notifications@github.com wrote:

Updated. Try v0.2.2

-- lloyd (thumb-typing)

On Mar 13, 2013, at 3:26 PM, scriby notifications@github.com wrote:

> Are you planning on updating npm with this change?
> 
> —
> Reply to this email directly or view it on GitHub.

—
Reply to this email directly or view it on
GitHubhttps://github.com/lloyd/node-memwatch/pull/27#issuecomment-14875386
.

**Pull request merged**
